INSERT INTO TB_POINT_POLICY
(POLICY_ID, MEMBER_ID, MAX_EARN_AMOUNT, MAX_BALANCE_AMOUNT)
VALUES
    (1, null, 10000, 100000);

INSERT INTO TB_POINT_POLICY
(POLICY_ID, MEMBER_ID, MAX_EARN_AMOUNT, MAX_BALANCE_AMOUNT)
VALUES
    (2, 'member1', 20000, 200000);